title: Barry Lim
description: 
  Barry is a professional Animator and Programmer with 15+ years in the media industry, handling animation, visual effects and games.<br>
  He is both an Artist working on creative animation and a programmer developing for media workflow pipelines.<br>
  In his spare time, he delves into other aspects of programming like Web development, Blockchain and Data Science.<br>

linkedin: https://www.linkedin.com/in/barry-lim-bb37903/
github:
  resume: portfolio/assets/Resume_Tech.pdf
  base: https://github.com/barlim3?tab=repositories
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
