title: Barry Lim
description: 
  Barry is a professional Animator and Programmer with 15+ years in the media industry, handling animation, visual effects and games.<br>
  He is both an Artist working on creative animation and a programmer developing for media workflow pipelines.<br>
  In his spare time, he delves into other aspects of programming like Web development, Blockchain and Data Science.<br>
  <a href="https://www.linkedin.com/in/barry-lim-bb37903/">LinkedIn</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
