title: Barry Lim
description: Barry is a professional Animator and Programmer with 15+ years in the media industry, handling animation, visual effects and games. He is both an Artist working on creative animation and a programmer developing for media workflow pipelines. In his spare time, he delves into other aspects of programming like Web development, Blockchain and Data Science.
google_analytics:
theme: jekyll-theme-cayman
